### ISSUE TITLE
视频分享失败

### ISSUE THREAD

**Issue by genanalucy** [ClydeTime/Quantumult#1]
获取视频动态成功
1️⃣ 观看(登录)任务
- 今日已经观看 2023-07-19 12:05:02
2️⃣ 分享任务
- 正在分享, aid=828593258

❗️bilibili, 错误!

TypeError: undefined is not an object (evaluating 'config.key.replace')

🔔bilibili, 结束! 🕛 0.806 秒

**Comment by genanalucy** [comment]
iOS 17.0 (21A5277j) NE v1.3.0-build781 40.69MB

**Comment by ClydeTime** [comment]
已修复
