### ISSUE TITLE
投币失败 日志提示非法访问

### ISSUE THREAD

**Issue by genanalucy** [ClydeTime/Quantumult#3]
5)
❚  #### 检查任务进行状况
❚  - 今日已登录
❚  - 今日已观看
❚  - 今日已分享
❚  ! 今日投币未完成
❚  #### 获取首页视频
❚  - 获取视频动态成功
❚  1️⃣ 观看(登录)任务
❚  - 今日已经观看 2023-10-19 12:06:19
❚  2️⃣ 分享任务
❚  - 今日已经分享 2023-10-19 12:06:19
❚  3️⃣ 投币任务
❚  - 获取关注列表成功
❚  - 获取投币视频成功
❚  - 作者: 艺能人金广发; 视频标题: 【今日睇真D】人族大帝挥金如土、
❚  - 投币成功
❚  - 获取关注列表成功
❚  - 获取投币视频成功
❚  - 作者: 艺能人金广发; 视频标题: 【汁蝶诗集】《剥橘》、
❚  - 投币成功
❚  - 获取关注列表成功
❚  - 获取投币视频成功
❚  - 作者: PuboH; 视频标题: 呲杆都是犯规？应该修改规则吗？【Dr.Dave台球教程】
❚  - 投币失败,失败原因 非法访问
❚  - 获取关注列表成功
❚  - 获取投币视频成功
❚  - 作者: PuboH; 视频标题: 【Dr.Dave台球教程】45颗球清台挑战
❚  - 投币失败,失败原因 非法访问

**Comment by genanalucy** [comment]
![IMG_2237](https://github.com/ClydeTime/Quantumult/assets/64259104/f321cc8a-f507-47c3-9220-37a8965eb99a)

**Comment by ClydeTime** [comment]
账号问题，多尝试即可。
